### PR TITLE
Add Mention component

### PR DESCRIPTION
**Pull request by shaodahong**
Ref: https://github.com/ant-design/ant-design/issues/19800

### CODE REVIEW

**Comment by shaodahong** [comment]
@zombieJ @import antd 引用样式有问题，找的不是 node_modules 而是相对路径

**Comment by shaodahong** [comment]
而且 `father` 好像不支持 compile `assets/index.less` 吧

**Comment by zombieJ** [comment]
嗯，得加一个这个：https://github.com/react-component/footer/blob/master/package.json#L34

**Comment by zombieJ** [comment]
@vagusX, merged. Please help to update codemod.

**Comment by zombieJ** [comment]
`+ @ant-design/compatible@0.0.1-alpha.6`

**Pull request merged**
